import { Question } from '@/lib/types';

export const questionBank: Question[] = [
  // ─── Software Engineer ────────────────────────────────────────────────────
  {
    id: 'fe-1',
    role: 'software engineer',
    difficulty: 'medium',
    text: 'Explain the difference between useMemo and useCallback in React. When would you use each, and what are common mistakes developers make with them?',
    topic: 'React Performance',
  },
  {
    id: 'fe-2',
    role: 'software engineer',
    difficulty: 'medium',
    text: 'What is the Critical Rendering Path in browsers? How would you optimize it for a large e-commerce homepage?',
    topic: 'Browser Performance',
  },
  {
    id: 'fe-3',
    role: 'software engineer',
    difficulty: 'medium',
    text: 'Describe how CSS specificity works. How does the cascade algorithm resolve conflicting styles, and how does the :is() selector affect specificity?',
    topic: 'CSS Fundamentals',
  },
  {
    id: 'fe-4',
    role: 'software engineer',
    difficulty: 'medium',
    text: 'What are Core Web Vitals (LCP, FID/INP, CLS)? How have you diagnosed and improved them in a real project?',
    topic: 'Core Web Vitals',
  },
  {
    id: 'fe-5',
    role: 'software engineer',
    difficulty: 'medium',
    text: 'Explain the JavaScript event loop. How do microtasks differ from macrotasks, and what happens when you mix Promises with setTimeout?',
    topic: 'JavaScript Runtime',
  },
  {
    id: 'fe-6',
    role: 'software engineer',
    difficulty: 'easy',
    text: 'Explain the difference between null and undefined in JavaScript. When would you intentionally use each one?',
    topic: 'JavaScript Fundamentals',
  },
  {
    id: 'fe-7',
    role: 'software engineer',
    difficulty: 'easy',
    text: 'What is the CSS box model? Explain the difference between content-box and border-box sizing.',
    topic: 'CSS Layout',
  },
  {
    id: 'fe-8',
    role: 'software engineer',
    difficulty: 'easy',
    text: 'How does React reconciliation work? What role do keys play in list rendering and why is using array index as a key often a bad idea?',
    topic: 'React Internals',
  },
  {
    id: 'fe-9',
    role: 'software engineer',
    difficulty: 'easy',
    text: 'What are the differences between var, let, and const? Explain hoisting and the temporal dead zone.',
    topic: 'JavaScript Scope',
  },
  {
    id: 'fe-10',
    role: 'software engineer',
    difficulty: 'easy',
    text: 'What is the difference between flexbox and CSS Grid? When would you choose one over the other?',
    topic: 'CSS Layout',
  },
  {
    id: 'fe-11',
    role: 'software engineer',
    difficulty: 'hard',
    text: 'Describe strategies you would use to improve the performance of a React application with slow initial load times and poor Core Web Vitals. Mention code splitting, SSR, and caching.',
    topic: 'Performance Optimization',
  },
  {
    id: 'fe-12',
    role: 'software engineer',
    difficulty: 'hard',
    text: 'What are ARIA roles and attributes? Walk through how you would make a custom modal dialog fully accessible to screen reader users, including focus management.',
    topic: 'Web Accessibility',
  },
  {
    id: 'fe-13',
    role: 'software engineer',
    difficulty: 'hard',
    text: 'Compare micro-frontend architectures. What problems do they solve, and what new complexities do they introduce at scale?',
    topic: 'Architecture',
  },
  {
    id: 'fe-14',
    role: 'software engineer',
    difficulty: 'hard',
    text: 'Explain Content Security Policy (CSP). How would you configure it for a Next.js app to prevent XSS without breaking third-party scripts?',
    topic: 'Web Security',
  },
  {
    id: 'fe-15',
    role: 'software engineer',
    difficulty: 'hard',
    text: 'How does server-side rendering differ from static site generation and incremental static regeneration in Next.js? When would you choose each?',
    topic: 'Next.js Rendering',
  },

  // ─── DevOps Engineer ──────────────────────────────────────────────────────
  {
    id: 'be-1',
    role: 'devops engineer',
    difficulty: 'medium',
    text: 'Compare REST and GraphQL. What are the concrete trade-offs in terms of network efficiency, schema evolution, and caching?',
    topic: 'API Design',
  },
  {
    id: 'be-2',
    role: 'devops engineer',
    difficulty: 'medium',
    text: 'What is database indexing? Explain how a B-tree index works, and describe scenarios where adding an index actually hurts performance.',
    topic: 'Database Optimization',
  },
  {
    id: 'be-3',
    role: 'devops engineer',
    difficulty: 'medium',
    text: 'Describe the difference between authentication and authorization. How would you implement JWT-based authentication with refresh token rotation in a Node.js API?',
    topic: 'Authentication',
  },
  {
    id: 'be-4',
    role: 'devops engineer',
    difficulty: 'medium',
    text: 'How would you design a rate-limiting system for a public API handling 10,000 requests per second? Discuss the token bucket vs. sliding window algorithms and the infrastructure required.',
    topic: 'System Design',
  },
  {
    id: 'be-5',
    role: 'devops engineer',
    difficulty: 'medium',
    text: 'Explain ACID properties in database transactions. How do you handle distributed transactions in a microservices architecture — compare 2PC, sagas, and outbox patterns.',
    topic: 'Distributed Systems',
  },
  {
    id: 'be-6',
    role: 'devops engineer',
    difficulty: 'easy',
    text: 'What is the difference between synchronous and asynchronous programming? Explain callbacks, Promises, and async/await with an example.',
    topic: 'Async Programming',
  },
  {
    id: 'be-7',
    role: 'devops engineer',
    difficulty: 'easy',
    text: 'What are HTTP status codes? Explain the difference between 400, 401, 403, 404, 409, and 500 and when you would return each.',
    topic: 'HTTP Fundamentals',
  },
  {
    id: 'be-8',
    role: 'devops engineer',
    difficulty: 'easy',
    text: 'Explain the difference between SQL and NoSQL databases. Give examples of when you would choose each.',
    topic: 'Database Fundamentals',
  },
  {
    id: 'be-9',
    role: 'devops engineer',
    difficulty: 'easy',
    text: 'What is middleware in Express.js? Explain the request-response cycle and how error-handling middleware differs from regular middleware.',
    topic: 'Node.js / Express',
  },
  {
    id: 'be-10',
    role: 'devops engineer',
    difficulty: 'easy',
    text: 'What is a foreign key constraint in a relational database? How does it enforce referential integrity?',
    topic: 'SQL Basics',
  },
  {
    id: 'be-11',
    role: 'devops engineer',
    difficulty: 'hard',
    text: 'Design a URL shortener service like bit.ly that can handle 100 million daily active users. Cover hashing strategy, database schema, caching, and analytics.',
    topic: 'System Design',
  },
  {
    id: 'be-12',
    role: 'devops engineer',
    difficulty: 'hard',
    text: 'Explain event sourcing and CQRS. What problems do they solve and what operational complexity do they add?',
    topic: 'Architecture Patterns',
  },
  {
    id: 'be-13',
    role: 'devops engineer',
    difficulty: 'hard',
    text: 'How does connection pooling work in databases? How do you tune pool size for a high-throughput Node.js application?',
    topic: 'Database Performance',
  },
  {
    id: 'be-14',
    role: 'devops engineer',
    difficulty: 'hard',
    text: 'Describe a zero-downtime deployment strategy for a monolithic backend with a breaking database schema change.',
    topic: 'DevOps / Deployment',
  },
  {
    id: 'be-15',
    role: 'devops engineer',
    difficulty: 'hard',
    text: 'What is the CAP theorem? How do systems like Cassandra, DynamoDB, and PostgreSQL position themselves relative to it?',
    topic: 'Distributed Systems',
  },

  // ─── Data Scientist ───────────────────────────────────────────────────────
  {
    id: 'da-1',
    role: 'data scientist',
    difficulty: 'medium',
    text: 'Explain SQL window functions. Write a query using ROW_NUMBER(), RANK(), and LAG() to compute month-over-month revenue growth per product category.',
    topic: 'Advanced SQL',
  },
  {
    id: 'da-2',
    role: 'data scientist',
    difficulty: 'medium',
    text: 'You receive a dataset with 30% missing values in a key numeric column. Walk through the strategies you would consider — deletion, imputation, and model-based approaches — with their trade-offs.',
    topic: 'Data Cleaning',
  },
  {
    id: 'da-3',
    role: 'data scientist',
    difficulty: 'medium',
    text: 'Describe how you would design and analyze a cohort retention analysis. What SQL structure or pandas logic would you use to produce a weekly retention matrix?',
    topic: 'Cohort Analysis',
  },
  {
    id: 'da-4',
    role: 'data scientist',
    difficulty: 'medium',
    text: 'Explain A/B testing from hypothesis definition to statistical conclusion. What is p-value, statistical power, and how do you handle multiple comparisons?',
    topic: 'A/B Testing',
  },
  {
    id: 'da-5',
    role: 'data scientist',
    difficulty: 'medium',
    text: 'When would you use pandas vs. SQL for data analysis? Describe a scenario where you would use each and explain the trade-offs in terms of scalability and expressiveness.',
    topic: 'Python vs SQL',
  },
  {
    id: 'da-6',
    role: 'data scientist',
    difficulty: 'easy',
    text: 'Write a SQL query to find the top 5 customers by total purchase amount from an orders table with columns: order_id, customer_id, amount, created_at.',
    topic: 'SQL Querying',
  },
  {
    id: 'da-7',
    role: 'data scientist',
    difficulty: 'easy',
    text: 'What is the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN? Give an example of when you would use each.',
    topic: 'SQL Joins',
  },
  {
    id: 'da-8',
    role: 'data scientist',
    difficulty: 'easy',
    text: 'When would you choose a bar chart over a line chart? Describe the key principles of effective data visualization you apply when building dashboards.',
    topic: 'Data Visualization',
  },
  {
    id: 'da-9',
    role: 'data scientist',
    difficulty: 'easy',
    text: 'What is the difference between mean, median, and mode? In what distributions does each become more or less useful?',
    topic: 'Statistics Basics',
  },
  {
    id: 'da-10',
    role: 'data scientist',
    difficulty: 'easy',
    text: 'Explain the GROUP BY clause in SQL. What is the difference between WHERE and HAVING? Give a practical example.',
    topic: 'SQL Aggregation',
  },
  {
    id: 'da-11',
    role: 'data scientist',
    difficulty: 'hard',
    text: 'Explain the difference between correlation and causation. Describe a difference-in-differences or regression discontinuity approach to determine whether a business intervention actually caused a metric change.',
    topic: 'Causal Inference',
  },
  {
    id: 'da-12',
    role: 'data scientist',
    difficulty: 'hard',
    text: 'Using pandas, how would you efficiently process and aggregate a 5GB CSV file that does not fit in memory? Discuss chunking, Dask, Polars, and when you would use each.',
    topic: 'Large-Scale Data',
  },
  {
    id: 'da-13',
    role: 'data scientist',
    difficulty: 'hard',
    text: 'What is data modeling? Compare star schema vs. snowflake schema for an analytics data warehouse, discussing query performance and maintenance trade-offs.',
    topic: 'Data Modeling',
  },
  {
    id: 'da-14',
    role: 'data scientist',
    difficulty: 'hard',
    text: 'How would you detect and handle outliers in a dataset used for a revenue forecasting model? What statistical and domain-knowledge approaches would you combine?',
    topic: 'Statistical Analysis',
  },
  {
    id: 'da-15',
    role: 'data scientist',
    difficulty: 'hard',
    text: 'Describe the data pipeline you would build to generate a daily executive dashboard. Cover ingestion, transformation, storage, and visualization layers.',
    topic: 'Data Engineering',
  },
];

export function getQuestionsForSession(role: string, difficulty: string): Question[] {
  const filtered = questionBank.filter(
    (q) => q.role === role && q.difficulty === difficulty
  );

  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, 5);
}
